---
- name: Deploy app from Docker Hub to remote EC2
  hosts: all
  become: true
  vars:
    docker_image: "vaibhavisugandhi1733/myflaskapp5:latest"
    app_name: myapp
    container_port: 5000
    host_port: 80

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the Docker stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
        state: present
        filename: docker

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add current user to docker group (non-root access)
      user:
        name: "{{ ansible_user | default(ansible_user_id) }}"
        groups: docker
        append: yes

    - name: Stop and remove old container
      shell: |
        docker ps -q --filter "name={{ app_name }}" | grep -q . && docker stop {{ app_name }} && docker rm {{ app_name }} || true
      ignore_errors: true

    - name: Remove old image
      shell: |
        docker images -q {{ docker_image }} | grep -q . && docker rmi -f {{ docker_image }} || true
      ignore_errors: true

    - name: Pull Docker image from DockerHub
      shell: docker pull {{ docker_image }}

    - name: Run Docker container
      shell: |
        docker run -d --name {{ app_name }} -p {{ host_port }}:{{ container_port }} {{ docker_image }}

    - name: Disable password SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Enable PubkeyAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'

    - name: Restart SSH
      service:
        name: ssh
        state: restarted

