- name: Setup SSH access
  hosts: localhost
  vars:
    remote_host: "3.111.52.97"
    remote_user: ubuntu
    ssh_key_path: /home/ubuntu/firstkey.pem
  tasks:
    - name: Generate SSH key if not exists
      shell: |
        [ -f {{ ssh_key_path }} ] || ssh-keygen -t rsa -f {{ ssh_key_path }} -N ""

    - name: Copy public key to remote host
      shell: |
        sshpass -p "{{ remote_pass | default('') }}" ssh-copy-id -o StrictHostKeyChecking=no -i {{ ssh_key_path }} {{ remote_user }}@{{ remote_host }}
      environment:
        SSHPASS: "{{ remote_pass | default('') }}"
      ignore_errors: yes

